Repository prabirshrestha/asyncomplete.vim, pull requests merged in 2020-10, with the labels that each got.

#218 add async-clj-omni
  README.md
Labels: source

#219 add nextword for English autocomplete
  README.md
Labels: source

#220 add asyncomplete-clang source
  README.md
Labels: source

#221 add asyncomplete-look source for dictionary
  README.md
Labels: source

#222 add ale source
  README.md
Labels: source

#223 add asyncomplete-gitcommit source
  README.md
Labels: source

#224 add ai powered tabnine source
  README.md
Labels: source

#227 Clear matches
  autoload/asyncomplete.vim
Labels: bug

#228 fix #196 where b:asyncomplete_triggers may not exist
  autoload/asyncomplete/utils/_on_change/textchangedp.vim
Labels: bug

#229 Revert "Clear matches"
  autoload/asyncomplete.vim
Labels: bug

#230 Clear matches and enable closing popup menu
  autoload/asyncomplete.vim
  autoload/asyncomplete/utils/_on_change/textchangedp.vim
Labels: bug

#233 add stale.yml
  .github/stale.yml
Labels: enhancement

#234 add github workflows for ci
  .github/workflows/linux_neovim.yml
  .github/workflows/linux_vim.yml
  .github/workflows/mac_neovim.yml
  .github/workflows/reviewdog.yml
  .github/workflows/windows_neovim.yml
  .github/workflows/windows_vim.yml
  .vintrc.yaml
  test/.themisrc
  test/asyncomplete.vimspec
Labels: enhancement
